//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnvioCorreosAPI.BaseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EnvioCorreosEntities2 : DbContext
    {
        public EnvioCorreosEntities2()
            : base("name=EnvioCorreosEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_EnvioCorreos> T_EnvioCorreos { get; set; }
    
        public virtual int Registrar_Correos(string destinatario, string copiaDestinatario, string asunto, string cuerpoMensaje, Nullable<System.DateTime> fechaHoraEnvio)
        {
            var destinatarioParameter = destinatario != null ?
                new ObjectParameter("Destinatario", destinatario) :
                new ObjectParameter("Destinatario", typeof(string));
    
            var copiaDestinatarioParameter = copiaDestinatario != null ?
                new ObjectParameter("CopiaDestinatario", copiaDestinatario) :
                new ObjectParameter("CopiaDestinatario", typeof(string));
    
            var asuntoParameter = asunto != null ?
                new ObjectParameter("Asunto", asunto) :
                new ObjectParameter("Asunto", typeof(string));
    
            var cuerpoMensajeParameter = cuerpoMensaje != null ?
                new ObjectParameter("CuerpoMensaje", cuerpoMensaje) :
                new ObjectParameter("CuerpoMensaje", typeof(string));
    
            var fechaHoraEnvioParameter = fechaHoraEnvio.HasValue ?
                new ObjectParameter("FechaHoraEnvio", fechaHoraEnvio) :
                new ObjectParameter("FechaHoraEnvio", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Registrar_Correos", destinatarioParameter, copiaDestinatarioParameter, asuntoParameter, cuerpoMensajeParameter, fechaHoraEnvioParameter);
        }
    }
}
